spring:
    application:
        name: spring-batch-application-h2
    datasource:
      url: jdbc:mysql://localhost:3306/contract_db
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
    batch:
      initialize-schema: ALWAYS
      job:
        enabled: false
    jpa:
      generate-ddl: true
         
app-batch:
    chunk-size: 1000
    expiry:


